// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: account.sql

package db

import (
	"context"
	"database/sql"
)

const addAccountBalance = `-- name: AddAccountBalance :exec
UPDATE accounts SET balance = balance+?
WHERE id = ?
`

type AddAccountBalanceParams struct {
	Amount int64  `db:"amount"`
	ID     uint64 `db:"id"`
}

func (q *Queries) AddAccountBalance(ctx context.Context, arg AddAccountBalanceParams) error {
	_, err := q.db.ExecContext(ctx, addAccountBalance, arg.Amount, arg.ID)
	return err
}

const createAccounts = `-- name: CreateAccounts :execresult
INSERT INTO accounts (
  owner, balance, currency
) VALUES (
  ?, ?, ?
)
`

type CreateAccountsParams struct {
	Owner    string `db:"owner"`
	Balance  int64  `db:"balance"`
	Currency string `db:"currency"`
}

func (q *Queries) CreateAccounts(ctx context.Context, arg CreateAccountsParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createAccounts, arg.Owner, arg.Balance, arg.Currency)
}

const deleteAccounts = `-- name: DeleteAccounts :exec
DELETE FROM accounts
WHERE id = ?
`

func (q *Queries) DeleteAccounts(ctx context.Context, id uint64) error {
	_, err := q.db.ExecContext(ctx, deleteAccounts, id)
	return err
}

const getAccount = `-- name: GetAccount :one
SELECT id, owner, balance, currency, created_at FROM accounts
WHERE id = ?
`

func (q *Queries) GetAccount(ctx context.Context, id uint64) (Account, error) {
	row := q.db.QueryRowContext(ctx, getAccount, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.Balance,
		&i.Currency,
		&i.CreatedAt,
	)
	return i, err
}

const getAccountsForUpdate = `-- name: GetAccountsForUpdate :many
SELECT id, owner, balance, currency, created_at FROM accounts
WHERE id IN (?,?)
FOR UPDATE
`

type GetAccountsForUpdateParams struct {
	ID   uint64 `db:"id"`
	ID_2 uint64 `db:"id_2"`
}

func (q *Queries) GetAccountsForUpdate(ctx context.Context, arg GetAccountsForUpdateParams) ([]Account, error) {
	rows, err := q.db.QueryContext(ctx, getAccountsForUpdate, arg.ID, arg.ID_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Account{}
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.Owner,
			&i.Balance,
			&i.Currency,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAccounts = `-- name: ListAccounts :many
SELECT id, owner, balance, currency, created_at FROM accounts
ORDER BY id
`

func (q *Queries) ListAccounts(ctx context.Context) ([]Account, error) {
	rows, err := q.db.QueryContext(ctx, listAccounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Account{}
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.Owner,
			&i.Balance,
			&i.Currency,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPagedAccounts = `-- name: ListPagedAccounts :many
SELECT id, owner, balance, currency, created_at FROM accounts
WHERE owner = ?
ORDER BY id
LIMIT ?
OFFSET ?
`

type ListPagedAccountsParams struct {
	Owner  string `db:"owner"`
	Limit  int32  `db:"limit"`
	Offset int32  `db:"offset"`
}

func (q *Queries) ListPagedAccounts(ctx context.Context, arg ListPagedAccountsParams) ([]Account, error) {
	rows, err := q.db.QueryContext(ctx, listPagedAccounts, arg.Owner, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Account{}
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.Owner,
			&i.Balance,
			&i.Currency,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAccount = `-- name: UpdateAccount :exec
UPDATE accounts SET owner = ?, balance = ?, currency = ?
WHERE id = ?
`

type UpdateAccountParams struct {
	Owner    string `db:"owner"`
	Balance  int64  `db:"balance"`
	Currency string `db:"currency"`
	ID       uint64 `db:"id"`
}

func (q *Queries) UpdateAccount(ctx context.Context, arg UpdateAccountParams) error {
	_, err := q.db.ExecContext(ctx, updateAccount,
		arg.Owner,
		arg.Balance,
		arg.Currency,
		arg.ID,
	)
	return err
}
