// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"time"
)

type Account struct {
	ID        uint64    `db:"id"`
	Owner     string    `db:"owner"`
	Balance   int64     `db:"balance"`
	Currency  string    `db:"currency"`
	CreatedAt time.Time `db:"created_at"`
}

type Entry struct {
	ID        uint64    `db:"id"`
	AccountID uint64    `db:"account_id"`
	Amount    int64     `db:"amount"`
	CreatedAt time.Time `db:"created_at"`
}

type Session struct {
	ID           string    `db:"id"`
	Username     string    `db:"username"`
	RefreshToken string    `db:"refresh_token"`
	UserAgent    string    `db:"user_agent"`
	ClientIp     string    `db:"client_ip"`
	IsBlocked    bool      `db:"is_blocked"`
	ExpiresAt    time.Time `db:"expires_at"`
	CreatedAt    time.Time `db:"created_at"`
}

type Transfer struct {
	ID            uint64    `db:"id"`
	FromAccountID uint64    `db:"from_account_id"`
	ToAccountID   uint64    `db:"to_account_id"`
	Amount        int64     `db:"amount"`
	CreatedAt     time.Time `db:"created_at"`
}

type User struct {
	Username          string       `db:"username"`
	HashedPassword    string       `db:"hashed_password"`
	FullName          string       `db:"full_name"`
	Email             string       `db:"email"`
	IsVerified        bool         `db:"is_verified"`
	PasswordChangedAt sql.NullTime `db:"password_changed_at"`
	CreatedAt         time.Time    `db:"created_at"`
}

type VerifyEmail struct {
	ID         uint64       `db:"id"`
	Username   string       `db:"username"`
	Email      string       `db:"email"`
	SecretCode string       `db:"secret_code"`
	IsUsed     bool         `db:"is_used"`
	CreatedAt  time.Time    `db:"created_at"`
	ExpiredAt  sql.NullTime `db:"expired_at"`
}
