// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"
)

type Account struct {
	ID        uint64    `db:"id"`
	Owner     string    `db:"owner"`
	Balance   int64     `db:"balance"`
	Currency  string    `db:"currency"`
	CreatedAt time.Time `db:"created_at"`
}

type Entry struct {
	ID        uint64    `db:"id"`
	AccountID uint64    `db:"account_id"`
	Amount    int64     `db:"amount"`
	CreatedAt time.Time `db:"created_at"`
}

type Transfer struct {
	ID            uint64    `db:"id"`
	FromAccountID uint64    `db:"from_account_id"`
	ToAccountID   uint64    `db:"to_account_id"`
	Amount        int64     `db:"amount"`
	CreatedAt     time.Time `db:"created_at"`
}
