// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	AddAccountBalance(ctx context.Context, arg AddAccountBalanceParams) error
	CreateAccounts(ctx context.Context, arg CreateAccountsParams) (sql.Result, error)
	CreateEntries(ctx context.Context, arg CreateEntriesParams) (sql.Result, error)
	CreateTransfers(ctx context.Context, arg CreateTransfersParams) (sql.Result, error)
	DeleteAccounts(ctx context.Context, id uint64) error
	DeleteEntries(ctx context.Context, id uint64) error
	DeleteTransfers(ctx context.Context, id uint64) error
	GetAccount(ctx context.Context, id uint64) (Account, error)
	GetAccountsForUpdate(ctx context.Context, arg GetAccountsForUpdateParams) ([]Account, error)
	GetEntries(ctx context.Context, id uint64) (Entry, error)
	GetTransfers(ctx context.Context, id uint64) (Transfer, error)
	ListAccounts(ctx context.Context) ([]Account, error)
	ListEntries(ctx context.Context) ([]Entry, error)
	ListPagedAccounts(ctx context.Context, arg ListPagedAccountsParams) ([]Account, error)
	ListTransfers(ctx context.Context) ([]Transfer, error)
	UpdateAccount(ctx context.Context, arg UpdateAccountParams) error
}

var _ Querier = (*Queries)(nil)
