// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	AddAccountBalance(ctx context.Context, arg AddAccountBalanceParams) error
	CreateAccounts(ctx context.Context, arg CreateAccountsParams) (sql.Result, error)
	CreateEntries(ctx context.Context, arg CreateEntriesParams) (sql.Result, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (sql.Result, error)
	CreateTransfers(ctx context.Context, arg CreateTransfersParams) (sql.Result, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (sql.Result, error)
	CreateVerifiyEmail(ctx context.Context, arg CreateVerifiyEmailParams) (sql.Result, error)
	DeleteAccounts(ctx context.Context, id uint64) error
	DeleteEntries(ctx context.Context, id uint64) error
	DeleteSession(ctx context.Context, id string) error
	DeleteTransfers(ctx context.Context, id uint64) error
	DeleteUser(ctx context.Context, username string) error
	GetAccount(ctx context.Context, id uint64) (Account, error)
	GetAccountsForUpdate(ctx context.Context, arg GetAccountsForUpdateParams) ([]Account, error)
	GetEntries(ctx context.Context, id uint64) (Entry, error)
	GetEntriesByAccount(ctx context.Context, arg GetEntriesByAccountParams) (Entry, error)
	GetSession(ctx context.Context, id string) (Session, error)
	GetTransfers(ctx context.Context, id uint64) (Transfer, error)
	GetUser(ctx context.Context, username string) (User, error)
	GetVerifiyEmail(ctx context.Context, id uint64) (VerifyEmail, error)
	GetVerifiyEmailByUsername(ctx context.Context, username string) (VerifyEmail, error)
	ListAccounts(ctx context.Context) ([]Account, error)
	ListAllAccountIdByUsername(ctx context.Context, username string) ([]uint64, error)
	ListEntries(ctx context.Context) ([]Entry, error)
	ListEntriesByAccountIdAndUsername(ctx context.Context, arg ListEntriesByAccountIdAndUsernameParams) ([]Entry, error)
	ListPagedAccounts(ctx context.Context, arg ListPagedAccountsParams) ([]Account, error)
	ListPagedUsers(ctx context.Context, arg ListPagedUsersParams) ([]User, error)
	ListTransfers(ctx context.Context) ([]Transfer, error)
	ListTransfersFromAccount(ctx context.Context, fromAccountID uint64) ([]Transfer, error)
	ListTransfersToAccount(ctx context.Context, toAccountID uint64) ([]Transfer, error)
	ListUsers(ctx context.Context) ([]User, error)
	UpdateAccount(ctx context.Context, arg UpdateAccountParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) error
	UpdateVerifyEmail(ctx context.Context, arg UpdateVerifyEmailParams) (sql.Result, error)
}

var _ Querier = (*Queries)(nil)
