// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: verify_email.sql

package db

import (
	"context"
	"database/sql"
)

const createVerifiyEmail = `-- name: CreateVerifiyEmail :execresult
INSERT INTO verify_emails (
  username, email, secret_code
) VALUES (
  ?, ?, ?
)
`

type CreateVerifiyEmailParams struct {
	Username   string `db:"username"`
	Email      string `db:"email"`
	SecretCode string `db:"secret_code"`
}

func (q *Queries) CreateVerifiyEmail(ctx context.Context, arg CreateVerifiyEmailParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createVerifiyEmail, arg.Username, arg.Email, arg.SecretCode)
}

const getVerifiyEmail = `-- name: GetVerifiyEmail :one
SELECT id, username, email, secret_code, is_used, created_at, expired_at FROM verify_emails 
WHERE id = ?
`

func (q *Queries) GetVerifiyEmail(ctx context.Context, id uint64) (VerifyEmail, error) {
	row := q.db.QueryRowContext(ctx, getVerifiyEmail, id)
	var i VerifyEmail
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.SecretCode,
		&i.IsUsed,
		&i.CreatedAt,
		&i.ExpiredAt,
	)
	return i, err
}
