// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: rpc_entries.proto

package pb

import (
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Entry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	AccountId     uint64                 `protobuf:"varint,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Amount        uint64                 `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	CreatedAt     *timestamp.Timestamp   `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Entry) Reset() {
	*x = Entry{}
	mi := &file_rpc_entries_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Entry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entry) ProtoMessage() {}

func (x *Entry) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_entries_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Entry.ProtoReflect.Descriptor instead.
func (*Entry) Descriptor() ([]byte, []int) {
	return file_rpc_entries_proto_rawDescGZIP(), []int{0}
}

func (x *Entry) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Entry) GetAccountId() uint64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *Entry) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Entry) GetCreatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// list all entries by account id schema
type AccountID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     int64                  `protobuf:"varint,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountID) Reset() {
	*x = AccountID{}
	mi := &file_rpc_entries_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountID) ProtoMessage() {}

func (x *AccountID) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_entries_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountID.ProtoReflect.Descriptor instead.
func (*AccountID) Descriptor() ([]byte, []int) {
	return file_rpc_entries_proto_rawDescGZIP(), []int{1}
}

func (x *AccountID) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

type EntryListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*Entry               `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntryListResponse) Reset() {
	*x = EntryListResponse{}
	mi := &file_rpc_entries_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntryListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntryListResponse) ProtoMessage() {}

func (x *EntryListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_entries_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntryListResponse.ProtoReflect.Descriptor instead.
func (*EntryListResponse) Descriptor() ([]byte, []int) {
	return file_rpc_entries_proto_rawDescGZIP(), []int{2}
}

func (x *EntryListResponse) GetEntries() []*Entry {
	if x != nil {
		return x.Entries
	}
	return nil
}

var File_rpc_entries_proto protoreflect.FileDescriptor

const file_rpc_entries_proto_rawDesc = "" +
	"\n" +
	"\x11rpc_entries.proto\x12\x02pb\x1a\x1fgoogle/protobuf/timestamp.proto\"\x89\x01\n" +
	"\x05Entry\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\x04R\taccountId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x04R\x06amount\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"*\n" +
	"\tAccountID\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\x03R\taccountId\"8\n" +
	"\x11EntryListResponse\x12#\n" +
	"\aentries\x18\x01 \x03(\v2\t.pb.EntryR\aentriesB-Z+github.com/shivangp0208/bank_application/pbb\x06proto3"

var (
	file_rpc_entries_proto_rawDescOnce sync.Once
	file_rpc_entries_proto_rawDescData []byte
)

func file_rpc_entries_proto_rawDescGZIP() []byte {
	file_rpc_entries_proto_rawDescOnce.Do(func() {
		file_rpc_entries_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_entries_proto_rawDesc), len(file_rpc_entries_proto_rawDesc)))
	})
	return file_rpc_entries_proto_rawDescData
}

var file_rpc_entries_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_rpc_entries_proto_goTypes = []any{
	(*Entry)(nil),               // 0: pb.Entry
	(*AccountID)(nil),           // 1: pb.AccountID
	(*EntryListResponse)(nil),   // 2: pb.EntryListResponse
	(*timestamp.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_rpc_entries_proto_depIdxs = []int32{
	3, // 0: pb.Entry.created_at:type_name -> google.protobuf.Timestamp
	0, // 1: pb.EntryListResponse.entries:type_name -> pb.Entry
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_rpc_entries_proto_init() }
func file_rpc_entries_proto_init() {
	if File_rpc_entries_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_entries_proto_rawDesc), len(file_rpc_entries_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_entries_proto_goTypes,
		DependencyIndexes: file_rpc_entries_proto_depIdxs,
		MessageInfos:      file_rpc_entries_proto_msgTypes,
	}.Build()
	File_rpc_entries_proto = out.File
	file_rpc_entries_proto_goTypes = nil
	file_rpc_entries_proto_depIdxs = nil
}
