// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: rpc_get_all_user.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetAllUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageNum       uint32                 `protobuf:"varint,1,opt,name=page_num,json=pageNum,proto3" json:"page_num,omitempty"`
	PageSize      uint64                 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllUserRequest) Reset() {
	*x = GetAllUserRequest{}
	mi := &file_rpc_get_all_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllUserRequest) ProtoMessage() {}

func (x *GetAllUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_get_all_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllUserRequest.ProtoReflect.Descriptor instead.
func (*GetAllUserRequest) Descriptor() ([]byte, []int) {
	return file_rpc_get_all_user_proto_rawDescGZIP(), []int{0}
}

func (x *GetAllUserRequest) GetPageNum() uint32 {
	if x != nil {
		return x.PageNum
	}
	return 0
}

func (x *GetAllUserRequest) GetPageSize() uint64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type GetAllUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          []*User                `protobuf:"bytes,1,rep,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllUserResponse) Reset() {
	*x = GetAllUserResponse{}
	mi := &file_rpc_get_all_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllUserResponse) ProtoMessage() {}

func (x *GetAllUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_get_all_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllUserResponse.ProtoReflect.Descriptor instead.
func (*GetAllUserResponse) Descriptor() ([]byte, []int) {
	return file_rpc_get_all_user_proto_rawDescGZIP(), []int{1}
}

func (x *GetAllUserResponse) GetUser() []*User {
	if x != nil {
		return x.User
	}
	return nil
}

var File_rpc_get_all_user_proto protoreflect.FileDescriptor

const file_rpc_get_all_user_proto_rawDesc = "" +
	"\n" +
	"\x16rpc_get_all_user.proto\x12\x02pb\x1a\n" +
	"user.proto\"K\n" +
	"\x11GetAllUserRequest\x12\x19\n" +
	"\bpage_num\x18\x01 \x01(\rR\apageNum\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x04R\bpageSize\"2\n" +
	"\x12GetAllUserResponse\x12\x1c\n" +
	"\x04user\x18\x01 \x03(\v2\b.pb.UserR\x04userB-Z+github.com/shivangp0208/bank_application/pbb\x06proto3"

var (
	file_rpc_get_all_user_proto_rawDescOnce sync.Once
	file_rpc_get_all_user_proto_rawDescData []byte
)

func file_rpc_get_all_user_proto_rawDescGZIP() []byte {
	file_rpc_get_all_user_proto_rawDescOnce.Do(func() {
		file_rpc_get_all_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_get_all_user_proto_rawDesc), len(file_rpc_get_all_user_proto_rawDesc)))
	})
	return file_rpc_get_all_user_proto_rawDescData
}

var file_rpc_get_all_user_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rpc_get_all_user_proto_goTypes = []any{
	(*GetAllUserRequest)(nil),  // 0: pb.GetAllUserRequest
	(*GetAllUserResponse)(nil), // 1: pb.GetAllUserResponse
	(*User)(nil),               // 2: pb.User
}
var file_rpc_get_all_user_proto_depIdxs = []int32{
	2, // 0: pb.GetAllUserResponse.user:type_name -> pb.User
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_rpc_get_all_user_proto_init() }
func file_rpc_get_all_user_proto_init() {
	if File_rpc_get_all_user_proto != nil {
		return
	}
	file_user_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_get_all_user_proto_rawDesc), len(file_rpc_get_all_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_get_all_user_proto_goTypes,
		DependencyIndexes: file_rpc_get_all_user_proto_depIdxs,
		MessageInfos:      file_rpc_get_all_user_proto_msgTypes,
	}.Build()
	File_rpc_get_all_user_proto = out.File
	file_rpc_get_all_user_proto_goTypes = nil
	file_rpc_get_all_user_proto_depIdxs = nil
}
