// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: service_simple_bank.proto

package pb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_service_simple_bank_proto protoreflect.FileDescriptor

const file_service_simple_bank_proto_rawDesc = "" +
	"\n" +
	"\x19service_simple_bank.proto\x12\x02pb\x1a\x15rpc_create_user.proto\x1a\x14rpc_login_user.proto\x1a\x15rpc_update_user.proto\x1a\x16rpc_verify_email.proto\x1a\x1cgoogle/api/annotations.proto2\xfb\x02\n" +
	"\n" +
	"SimpleBank\x12U\n" +
	"\n" +
	"CreateUser\x12\x15.pb.CreateUserRequest\x1a\x16.pb.CreateUserResponse\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/api/v1/users\x12X\n" +
	"\tLoginUser\x12\x14.pb.LoginUserRequest\x1a\x15.pb.LoginUserResponse\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/api/v1/users/login\x12`\n" +
	"\n" +
	"UpdateUser\x12\x15.pb.UpdateUserRequest\x1a\x16.pb.UpdateUserResponse\"#\x82\xd3\xe4\x93\x02\x1d:\x01*2\x18/api/v1/users/{username}\x12Z\n" +
	"\x0fVerifyUserEmail\x12\x16.pb.VerifyEmailRequest\x1a\x17.pb.VerifyEmailResponse\"\x16\x82\xd3\xe4\x93\x02\x10\x12\x0e/api/v1/verifyB-Z+github.com/shivangp0208/bank_application/pbb\x06proto3"

var file_service_simple_bank_proto_goTypes = []any{
	(*CreateUserRequest)(nil),   // 0: pb.CreateUserRequest
	(*LoginUserRequest)(nil),    // 1: pb.LoginUserRequest
	(*UpdateUserRequest)(nil),   // 2: pb.UpdateUserRequest
	(*VerifyEmailRequest)(nil),  // 3: pb.VerifyEmailRequest
	(*CreateUserResponse)(nil),  // 4: pb.CreateUserResponse
	(*LoginUserResponse)(nil),   // 5: pb.LoginUserResponse
	(*UpdateUserResponse)(nil),  // 6: pb.UpdateUserResponse
	(*VerifyEmailResponse)(nil), // 7: pb.VerifyEmailResponse
}
var file_service_simple_bank_proto_depIdxs = []int32{
	0, // 0: pb.SimpleBank.CreateUser:input_type -> pb.CreateUserRequest
	1, // 1: pb.SimpleBank.LoginUser:input_type -> pb.LoginUserRequest
	2, // 2: pb.SimpleBank.UpdateUser:input_type -> pb.UpdateUserRequest
	3, // 3: pb.SimpleBank.VerifyUserEmail:input_type -> pb.VerifyEmailRequest
	4, // 4: pb.SimpleBank.CreateUser:output_type -> pb.CreateUserResponse
	5, // 5: pb.SimpleBank.LoginUser:output_type -> pb.LoginUserResponse
	6, // 6: pb.SimpleBank.UpdateUser:output_type -> pb.UpdateUserResponse
	7, // 7: pb.SimpleBank.VerifyUserEmail:output_type -> pb.VerifyEmailResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_service_simple_bank_proto_init() }
func file_service_simple_bank_proto_init() {
	if File_service_simple_bank_proto != nil {
		return
	}
	file_rpc_create_user_proto_init()
	file_rpc_login_user_proto_init()
	file_rpc_update_user_proto_init()
	file_rpc_verify_email_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_simple_bank_proto_rawDesc), len(file_service_simple_bank_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_simple_bank_proto_goTypes,
		DependencyIndexes: file_service_simple_bank_proto_depIdxs,
	}.Build()
	File_service_simple_bank_proto = out.File
	file_service_simple_bank_proto_goTypes = nil
	file_service_simple_bank_proto_depIdxs = nil
}
